using Microsoft.AspNetCore.Http;

using System;
using System.ComponentModel.DataAnnotations;

namespace WebTool
{
    public class HtmlElementUpdateImageModel
    {
        [Required]
        public Guid AutoGeneratedId { get; set; }

        [Required]
        public string ElementId { get; set; }

        [Required]
        public IFormFile Image { get; set; }

        [Required]
        [Url]
        public string Url { get; set; }
    }
}
