using System;

namespace WebTool
{
    public class Request
    {
        public Guid AutoGeneratedId { get; set; }
        public int TaskReferenceId { get; set; }
        public string AuthorId { get; set; }
        public string Url { get; set; }
        public string DeveloperName { get; set; }
        public DateTime? TimeOfSubmit { get; set; }
        public RequestStatus Status { get; set; }

        public Request()
        {
            AutoGeneratedId = Guid.NewGuid();
            Status = RequestStatus.PMInProgress;
        }
    }
}