using System;
using System.ComponentModel.DataAnnotations;

namespace WebTool
{
    public class RequestCreateModel
    {
        public Guid AutoGeneratedId { get; set; } = Guid.NewGuid();

        [Required]
        public int? TaskReferenceId { get; set; }

        [Required]
        [Url]
        public string Url { get; set; }
    }
}