using System;
using System.Collections.Generic;
using System.Linq;

namespace WebTool
{
    public class RequestCollection : List<Request>
    {
        public RequestCollection(IEnumerable<Request> requests) : base(requests) { }

        public Request FindByAutoGeneratedId(Guid autoGeneratedId)
        {
            return this.SingleOrDefault(r => r.AutoGeneratedId == autoGeneratedId);
        }
    }
}